### ISSUE TITLE
Store is undefined with new version of cache-manager.

### ISSUE THREAD

**Issue by saachinsiva** [Tirke/node-cache-manager-ioredis#43]
Hi

Thanks for rewriting this package. We updated the cache-manager to the latest version([5.0.1](https://www.npmjs.com/package/cache-manager/v/5.0.1))  and things started breaking ever since. Please see below the error we get.

```
private configRedisStore(): void {
		const configObj: any = {
			store: IoRedisStore,
			clusterConfig: null,
			host: null,
			port: null,
			ttl: null,
			connectTimeout: 5000,
			tls: null,
			// eslint-disable-next-line camelcase
			socket_keepalive: true
		};

		if (
			this.dsConfig.node.app_env.toUpperCase() === DSServerConstants.PROD_ENV ||
			this.dsConfig.node.app_env.toUpperCase() === DSServerConstants.UAT_ENV ||
			this.dsConfig.node.app_env.toUpperCase() === DSServerConstants.DEV_ENV
		) {
			configObj.tls = {};
		}

		if (this.dsConfig.aws.elasticCache.clusterConfig) {
			configObj.clusterConfig = this.dsConfig.aws.elasticCache.clusterConfig;
		} else {
			configObj.host = this.dsConfig.aws.elasticCache.host;
			configObj.port = this.dsConfig.aws.elasticCache.port;
		}

		// Promisify all the functions
		this.redisCache = caching(configObj);
		const cacheStore: Store = this.redisCache.store as Store;
		this.redisClient = cacheStore.getClient();
	}
```

Error 

> 2022-10-14 10:32:25.831 [error] - TypeError: Cannot read properties of undefined (reading 'getClient')

It looks like the cacheStore is undefined.

**Comment by Tirke** [comment]
Hello @saachinsiva thanks for opening this issue. The new version of cache manager is a major bump and I need to invest a bit of time checking and updating everything to handle the changes. I'll do my best to look at it soon.

**Comment by curtdept** [comment]
@saachinsiva IoRedisStore.create to get a "RedisStore" thats compatible

**Comment by NarHakobyan** [comment]
getting error too.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/1781506/196949350-ed57de27-09ca-4f68-bbe7-deb6fc155ada.png">

**Comment by Tirke** [comment]
@NarHakobyan @saachinsiva I've just published `3.0.0` that is the new version of this package, working with the new `cache-manager` version > 5.

**Comment by guotingchao** [comment]
Use the version 3.0.0, Getting same error 

> getting error too.
> 
> <img alt="image" width="590" src="https://user-images.githubusercontent.com/1781506/196949350-ed57de27-09ca-4f68-bbe7-deb6fc155ada.png">

Use the version 3.0.0, But getting the same error.

**Comment by Tirke** [comment]
@guotingchao
1. The API for this package changed please check the README to see how initialisation is done now
2. Nestjs is not compatible with the new cache-manager version you can follow this issue here https://github.com/node-cache-manager/node-cache-manager/issues/210. Please stay on v4 of `cache-manager` and v2 of this one here.
